version: '3'
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'

  muffet:
    image: raviqqe/muffet
    links:
      - 'app'
